name:                1inguini-github-io
version:             0.1.0.0
github:              "1inguini/1inguini.github.io"
license:             BSD3
author:              "linguini"
maintainer:          "9647142@gmail.com"
copyright:           "Copyright: © 2020 linguini"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/1inguini/1inguini.github.io#readme>

dependencies: 
- name: base
  version: ">= 4.7 && < 5"
  mixin:
  - hiding (Prelude)
- name: rio
  # mixin:
  # - hiding (RIO)
  # - (RIO as Prelude)
- hakyll
- lucid
- hint
- binary
- optics
- generic-optics
- data-default-class

default-extensions:
# - NoImplicitPrelude
- OverloadedStrings
- GeneralizedNewtypeDeriving
- DuplicateRecordFields
# - ExistentialQuantification

library:
  source-dirs:
  - templates
  - src
  when:
  - condition: false
    other-modules: Paths_1inguini_github_io

executables:
  site:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -O0
    - -dynamic
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - 1inguini-github-io
    when:
    - condition: false
      other-modules: Paths_1inguini_github_io
    

tests:
  posts: # only for haskell-languag-eserver to work for posts
    main:                Index.hs
    source-dirs:
    - .
    #- posts
    - pages
    - templates
    # dependencies:
    # - 1inguini-github-io
    when:
    - condition: false
      other-modules: Paths_1inguini_github_io

  1inguini-github-io-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 1inguini-github-io
    when:
    - condition: false
      other-modules: Paths_1inguini_github_io

