{-# LANGUAGE OverloadedStrings #-}

-- | basic templates
module Template
  ( module Lucid,
    template,
  )
where

import Lucid
import Data.Text (Text)

template :: Text -> Html () -> Html ()
template title content = doctypehtml_ $ do
  head_ [] $ do
    title_ $ toHtmlRaw title
    meta_ [name_ "linguini", content_ "blog"]
    meta_ [name_ "generator", content_ "Hakyll"]
    meta_ [charset_ "utf-8"]
    meta_ [name_ "viewport", content_ "width=device-width, initial-scale=1"]
    meta_ [httpEquiv_ "Content-Style-Type", content_ "text/css"]
    meta_ [httpEquiv_ "Content-Script-Type", content_ "text/javascript"]
    -- link_ [rel_ "stylesheet", href_ "https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css"]
    link_ [rel_ "stylesheet", href_ "https://cdn.jsdelivr.net/npm/@exampledev/new.css/new.min.css"]
    body_ $ do
      header_ $ h1_ "linguiniの✨ブログ✨"
      main_ content
      footer_ $ "Copyright: © 2020 linguini. Site proudly generated by " <> a_ [href_ "http://jaspervdj.be/hakyll"] "Hakyll"

