# This is a basic workflow to help you get started with Actions

name: build Hakyll site

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'pages/**'
      - 'posts/**'
      - 'template/**'
      - 'src/**'
      - 'Main.hs'
      - '!docs/**'

  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: executable last modified timestamp
        id: timestamp
        run: echo "::set-output modified="$(stat --format="%Y" $(find ./.stack-work -name LICENSE))

      - name: use cache ~/.stack
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: stack-${{ runner.os }}-${{ env.cache-name }} #-${{ steps.timestamp.modified }}
          # restore-keys: |
          #   stack-${{ runner.os }}-${{ env.cache-name }}-

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.4' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defalts to 'latest'
          enable-stack: true
          stack-version: 'latest'

      - name: execute generator
        run: |
          stack --system-ghc run rebuild

      - name: configure git
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email "${GITHUB_EMAIL}"
          git remote set-url origin https://${{ github.actor }}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: add and commit
        run: |
          git add -f --verbose docs
          git commit --allow-empty -m "(⋈◍＞◡＜◍)。✧♡ automatic build by GitHub Actions"
          git push origin master
